# 服务配置
server:
  port: 10008
# Spring配置
spring:
  # 数据源配置
  datasource:
    #oracle
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: vue
    password: cape
    #mysql
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:3306/database?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    #username: root
    #password: root
